-- require("plugins.tokyonight")
require("plugins.catppuccin")
require("plugins.blink")
require("plugins.bufferline")
require("plugins.conform")
-- require("plugins.copilot")
require("plugins.treesitter")
require("plugins.snippets")
require("plugins.mini")
require("plugins.lualine")
require("plugins.markdown")
require("plugins.gitsigns")
require("plugins.snacks")
require("plugins.flash")
require("plugins.undotree")
-- require("plugins.avante")
-- require("plugins.sidekick")
