-- require("plugins.tokyonight")
require("plugins.catppuccin")
require("plugins.mini")
require("plugins.blink")
require("plugins.conform")
require("plugins.copilot")
require("plugins.treesitter")
require("plugins.snippets")
require("plugins.lualine")
require("plugins.markdown")
require("plugins.gitsigns")
require("plugins.snacks")
require("plugins.flash")
require("plugins.undotree")
require("plugins.difftool")
require("plugins.bufferline")
require("plugins.oil")
require("plugins.lazydev")
require("plugins.crisp")
-- require("plugins.opencode")
-- require("plugins.avante")
require("plugins.sidekick")
require("plugins.jujutsu")
require("plugins.diffview")
