require("plugins.tokyonight")
-- require("plugins.catppuccin")
require("plugins.treesitter")
require("plugins.mini")
require("plugins.conform")
require("plugins.markdown")
require("plugins.gitsigns")
require("plugins.snacks")
-- require("plugins.sidekick")
